# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'
        cache: 'gradle'
    - run: java -version    
    - run: chmod 777 gradlew
    - run: ./gradlew build --no-daemon
    - run: | 
            cd build/libs
            ls -lrt
    - uses: actions/upload-artifact@v3
      with:
        name: myartifact
        path: build/libs/DevOps-as-a-service-0.0.1-SNAPSHOT.jar
        
  publish:
  
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAVZTOI5R4OPNVJK57
        aws-secret-access-key: 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
        aws-region: us-east-1
        
    - run: aws --version
    - run: aws s3 ls
    - uses: actions/download-artifact@v3
      with:
        name: myartifact
        
    - run: ls -lrt
    - run: aws s3 cp DevOps-as-a-service-0.0.1-SNAPSHOT.jar s3://parthprojectbucket/newapp-${GITHUB_RUN_ID}.jar
    
  deploy:
  
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
    
    - run: echo "${GITHUB_RUN_ID}"
    
        
            
